**1)Create a 3x3x3 array with random values**

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.60855349 0.11054094 0.04340374]
  [0.78616576 0.67886106 0.69121945]
  [0.28858046 0.78520553 0.93262018]]

 [[0.9243774  0.33761697 0.51953139]
  [0.44820846 0.08540484 0.53312592]
  [0.38342833 0.74102728 0.22227155]]

 [[0.57820135 0.24177455 0.19600527]
  [0.92933395 0.16751928 0.7418358 ]
  [0.12418601 0.12458035 0.35223613]]]


**2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [4]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**3)Create a 8x8 matrix and fill it with a checkerboard pattern**

In [7]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4) Normalize a 5x5 random matrix**

In [6]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.4211883  0.20827996 0.1769904  0.72637692 0.99786777]
 [0.8441578  0.0244611  0.32240658 0.76582227 0.91924972]
 [0.98915909 0.3178972  0.80560303 1.         0.76559416]
 [0.63352056 0.27602401 0.         0.10182982 0.80705345]
 [0.7173383  0.2120084  0.62918013 0.20324593 0.22158928]]


**5)How to find common values between two arrays?**

In [8]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


**6.How to get the dates of yesterday, today and tomorrow?**

In [9]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


**7. Consider two random array A and B, check if they are equal**

In [10]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


**8) Create random vector of size 10 and replace the maximum value by 0**

In [11]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.74032721 0.70053976 0.24784702 0.98229239 0.57234932 0.82833813
 0.16143217 0.1960238  0.26837346 0.74641451]
Maximum value replaced by 0:
[0.74032721 0.70053976 0.24784702 0.         0.57234932 0.82833813
 0.16143217 0.1960238  0.26837346 0.74641451]


**9. How to print all the values of an array?**

In [31]:
Z = np.random.random((10,10))
print(Z)

[[0.57447446 0.81409595 0.4303208  0.04649168 0.75085519 0.00928692
  0.50140556 0.49258038 0.20218232 0.05170433]
 [0.12729814 0.11179537 0.0884464  0.77150763 0.0392473  0.61492476
  0.10464994 0.24637868 0.24826476 0.32213772]
 [0.30308519 0.93738269 0.12312154 0.03807545 0.12972218 0.19141321
  0.91632178 0.18974957 0.78200979 0.43134681]
 [0.59720541 0.27446855 0.2280631  0.5524955  0.04877026 0.36401344
  0.02137964 0.30726561 0.91497318 0.75771907]
 [0.62797927 0.4494529  0.35740984 0.85685961 0.08732473 0.6550811
  0.43457437 0.87007718 0.965347   0.22994621]
 [0.35167067 0.48294547 0.05142765 0.94816314 0.16540673 0.36149734
  0.3608371  0.94823349 0.97886461 0.63338956]
 [0.48392282 0.83473023 0.59649812 0.81680606 0.99122791 0.52806293
  0.61647667 0.52702713 0.99485263 0.92416305]
 [0.64540994 0.39190717 0.45114536 0.49797691 0.10060507 0.31055036
  0.52655297 0.96233518 0.68837745 0.32986168]
 [0.37230127 0.9812939  0.86656331 0.46997085 0.94605412 0.99676672
  0.09320099 

**10.Subtract the mean of each row of a matrix**

In [19]:
X = np.random.rand(6, 12)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.52091687,  0.17074323,  0.23782003,  0.21930011, -0.58820952,
         0.13297855, -0.22001761,  0.19292278, -0.1571869 ,  0.36277452,
        -0.06713813,  0.23692981],
       [ 0.07804583, -0.17453318,  0.06992351, -0.43030721, -0.03449747,
         0.33137193, -0.48928548,  0.10496059,  0.41002951,  0.00425642,
         0.02386282,  0.10617272],
       [ 0.28415191, -0.24189969, -0.4207422 ,  0.32219376, -0.16916541,
        -0.27802785, -0.08265501,  0.35116795,  0.39061216,  0.24953356,
        -0.19920233, -0.20596686],
       [-0.26573651,  0.14991995, -0.26588652, -0.28601901, -0.27576474,
         0.1333644 ,  0.48954366,  0.04634022,  0.01897654, -0.33813621,
         0.00528459,  0.58811363],
       [-0.14496482,  0.1400827 , -0.19252231,  0.09062505,  0.24242327,
        -0.14116768, -0.32982122,  0.26278728, -0.04415845, -0.05012207,
        -0.28671424,  0.45355248],
       [-0.05865816, -0.26621719,  0.40554455,  0.10288903,  0.01250016,
         0.34926469, -

**11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [22]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 3. 3. 3. 2. 4. 2. 5. 3.]


**12.How to get the diagonal of a dot product?**

In [23]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([54, 23, 42])

**13.How to find the most frequent value in an array?**

In [24]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[9 7 3 1 9 1 6 8 0 2 3 7 2 8 1 2 2 8 3 2 2 3 4 8 0 7 6 0 7 5 3 6 8 0 8 6 1
 6 1 4 8 9 2 5 6 4 4 3 4 6]
rank: 2


**14.How to get the n largest values of an array**

In [25]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


**15.How to create a record array from a regular array?**

In [30]:
import numpy as np
arra1 = np.array([("yogi", 88.5, 90),
                 ("tejashwini", 87, 99),
             ("Anand", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['yogi' '88.5' '90']
 ['tejashwini' '87' '99']
 ['Anand' '85.5' '91']]

Record array;
[(b'yogi', 88.5, 90) (b'tejashwini', 87. , 99) (b'Anand', 85.5, 91)]
