In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [3]:
data=pd.read_csv('train.csv')
data.head()


PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [4]:
data.head()


PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [5]:
data.tail()

PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
884          887         0       2  ...  13.00   NaN         S
885          888         1       1  ...  30.00   B42         S
886          889         0       3  ...  23.45   NaN         S
887          890         1       1  ...  30.00  C148         C
888          891         0       3  ...   7.75   NaN         Q

[5 rows x 12 columns]

In [6]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [7]:
len(data)

889


1.Since most of the entries of cabin are null, we drop it

2.Name does not have any significance so drop it

In [8]:
data.drop(['Name','Cabin'], axis = 1, inplace = True)

In [9]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [10]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [11]:
le = LabelEncoder()

In [12]:
data['Sex'] = le.fit_transform(data.Sex)

In [13]:
data['Ticket'] = le.fit_transform(data.Ticket)

In [14]:
data['Embarked'] = le.fit_transform(data.Embarked)

In [15]:
data = data.astype(np.int64)

In [16]:
data.dtypes

PassengerId    int64
Survived       int64
Pclass         int64
Sex            int64
Age            int64
SibSp          int64
Parch          int64
Ticket         int64
Fare           int64
Embarked       int64
dtype: object

In [17]:
def NaiveBayes(x,y):
    x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)
    clf = GaussianNB()
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    print("Accuracy_score:",accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))


###Model 1 Survived Vs Remaining DV

In [18]:
y = data['Survived']

In [19]:
x = data[['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked']]

In [20]:
print("Survived Vs Remaining DV")
NaiveBayes(x,y)

Survived Vs Remaining DV
Accuracy_score: 0.7602996254681648
Confusion Matrix:
 [[125  32]
 [ 32  78]]


In [21]:
models = ['Pclass','Sex','SibSp','Parch','Embarked']

In [22]:
for col in models :
    y = data[col]
    x = data.drop(col,axis=1)
    print("")
    print(col,"Vs Remaining Dv")
    NaiveBayes(x,y)


Pclass Vs Remaining Dv
Accuracy_score: 0.7528089887640449
Confusion Matrix:
 [[ 52  14   4]
 [  5  33  11]
 [  6  26 116]]

Sex Vs Remaining Dv
Accuracy_score: 0.7153558052434457
Confusion Matrix:
 [[ 52  46]
 [ 30 139]]

SibSp Vs Remaining Dv
Accuracy_score: 0.6554307116104869
Confusion Matrix:
 [[147  16   2  16   1   0   0]
 [ 34  20   0  11   0   0   0]
 [  6   1   1   0   0   0   0]
 [  2   0   0   2   3   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]

Parch Vs Remaining Dv
Accuracy_score: 0.6554307116104869
Confusion Matrix:
 [[163   9   2  11  13]
 [ 20   5   3   8   4]
 [ 11   7   7   1   1]
 [  1   0   0   0   0]
 [  0   0   0   1   0]]

Embarked Vs Remaining Dv
Accuracy_score: 0.6591760299625468
Confusion Matrix:
 [[ 23   3  23]
 [  0  12  10]
 [ 24  31 141]]
